name: Notify on New PR

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification
        run: |
          curl -X POST https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=803a3e0c-019e-4e4b-889b-dbc944803b77 \
          -H "Content-Type: application/json" \
          -d '{
                "msgtype": "text",
                "text": {
                    "content": "PR已创建：\n\n链接：${{ github.event.pull_request.html_url }}\n\n作者：${{ github.event.pull_request.user.login }}\n\n标题：${{ github.event.pull_request.title }}\n\n描述：${{ github.event.pull_request.body }}"
                }
              }'
